API docs for ToxCore and related libraries
TokTok/website pull request #99
Opened 2018-02-01 14:41 UTC by SkyzohKey

2018-02-04 17:52 UTC, iphydf requested changes
Please fix the lint warnings.

2018-02-04 17:52 UTC, iphydf commented on toktok/get-started.md
> +- [ToxCore API Documentation by SkyzohKey](http://ricinapp.github.io/toxcore/toxcore/index.htm)
toktok/get-started.md:17: MD030 Spaces after list markers

2018-02-04 17:52 UTC, iphydf commented on toktok/get-started.md
> +- [ToxEncryptSave API Documentation by SkyzohKey](http://ricinapp.github.io/toxencryptsave/toxencryptsave/index.htm)
toktok/get-started.md:18: MD030 Spaces after list markers

2018-06-05 21:50 UTC, iphydf commented
Would it make sense to host these docs on the website instead? I.e. making their generation part of the website build process?

2018-06-06 16:59 UTC, sudden6 commented
I think docs on the website would be very cool, if possible with a selectable version like for cmake: https://cmake.org/cmake/help/v3.3/command/install.html

2018-06-08 05:20 UTC, SkyzohKey commented
Summoning @naxuroqa here as I guess he updated the VAPI interface and so he can gives you more up to date docs :)

2018-06-08 17:03 UTC, naxuroqa commented
The docs for the vala bindings used by venom are at https://naxuroqa.github.io/vala-toxcore-c/
They can be auto generated from the vapi files.
I adapted most comments to be usable for valadoc. As far as I can test them with travis they all work.
The vapi files themself are at https://github.com/naxuroqa/vala-toxcore-c

2018-06-08 21:06 UTC, naxuroqa commented
The question would be what kind of documentation you want.
While the vala documentation might be useful for some, I guess something like a doxygen generated doc would be better for anyone using the c-api.

I'm all for docs on the website either way, if possible even with (small) usage examples.

2018-08-12 16:02 UTC, iphydf commented
@naxuroqa I'd be happy linking to externally hosted API docs from the integrations page. I was hoping to have some API docs built from tox.h, but not using doxygen (too much overhead). A simple html page that fits into our template would be nice.

2018-08-19 22:41 UTC, iphydf requested changes
Please fix the lint warnings.

> *[Reviewable](https://reviewable.io/reviews/toktok/website/99#-:-LKJLFYl92UxIzXpSmQW:bf4engl)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)



<!-- Sent from Reviewable.io -->

2018-08-19 22:41 UTC, iphydf reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/toktok/website/99)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @iphydf)



<!-- Sent from Reviewable.io -->

2025-01-21 23:07 UTC, closed without merging